version: '3.1'
services:
  postgresql:
    image: postgres:latest
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=aapl
      - POSTGRES_PASSWORD=1111